openapi: 3.0.0
info:
  title: Exment API
  version: '1.0'
  description: "ExmentのWeb APIリファレンスです。  \nアプリの登録方法や、アクセストークンの取得方法、スコープ一覧は[こちら](https://exment.net/docs/#/ja/api)をご参照ください。  \nその他マニュアルは、[こちら](https://exment.net/docs/#/ja/)をご参照ください。\n\nこちらはExmentのRestAPIの仕様書になります。OpenAPI形式で作成されています。"
  termsOfService: 'https://exment.net'
  contact:
    email: info@exment.net
servers:
  - url: 'http://localhost/admin'
paths:
  /api/version:
    get:
      summary: システムバージョン情報取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    description: Exmentバージョン
                required:
                  - version
              examples:
                Example:
                  value:
                    version: v3.0.1
      description: |
        #### 処理概要
        * インストールしているExmentのシステムバージョンを取得

        #### Exment権限(Permission)
        なし

        #### APIスコープ(scope)
        なし

        #### 対応バージョン
        v1.1.0
      security:
        - OAuth2認証: []
      operationId: get-version
  /api/me:
    get:
      summary: ログインユーザー情報取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomValue'
              examples:
                Example:
                  value:
                    id: 1
                    suuid: b6ba6222ebb2aa455521
                    parent_type: null
                    parent_id: null
                    value:
                      email: admin@foobar.test
                      user_code: admin
                      user_name: admin
                    created_at: '2019-11-13 17:00:38'
                    updated_at: '2019-11-13 17:06:11'
                    deleted_at: null
                    deleted_user_id: null
                    created_user_id: null
                    updated_user_id: '1'
                    label: admin
      description: |-
        #### 処理概要
        * ログインユーザー自身のユーザー情報を取得する

        #### Exment権限(Permission)
        なし

        #### APIスコープ(scope)
        + me

        #### 対応バージョン
        v1.1.0
      security:
        - OAuth2認証: []
      operationId: get-me
  /api/table:
    get:
      summary: カスタムテーブル一覧
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CustomTable'
                  - properties:
                      data:
                        $ref: ''
                type: object
              examples:
                Example:
                  value:
                    current_page: 1
                    data:
                      - id: 3
                        suuid: 4131b102c1c3f3879114
                        table_name: base_info
                        table_view_name: 基本情報
                        description: null
                        system_flg: '1'
                        showlist_flg: '1'
                        order: '0'
                        options:
                          icon: fa-building
                          comment_flg: '0'
                          attachment_flg: '0'
                          one_record_flg: '1'
                          search_enabled: '0'
                          all_user_accessable_flg: '1'
                        created_at: '2019-11-13 17:00:11'
                        updated_at: '2019-11-13 17:00:11'
                        created_user_id: null
                        updated_user_id: null
                      - id: 4
                        suuid: 54e448bbd64731a061aa
                        table_name: user
                        table_view_name: ユーザー
                        description: null
                        system_flg: '1'
                        showlist_flg: '1'
                        order: '0'
                        options:
                          icon: fa-user
                          comment_flg: '0'
                          attachment_flg: '0'
                          one_record_flg: '0'
                          search_enabled: '1'
                          all_user_accessable_flg: '1'
                        created_at: '2019-11-13 17:00:11'
                        updated_at: '2019-11-13 17:00:11'
                        created_user_id: null
                        updated_user_id: null
                      - id: 5
                        suuid: e338ce723f7da614d377
                        table_name: organization
                        table_view_name: 組織
                        description: null
                        system_flg: '1'
                        showlist_flg: '1'
                        order: '0'
                        options:
                          icon: fa-sitemap
                          comment_flg: '0'
                          attachment_flg: '0'
                          one_record_flg: '0'
                          search_enabled: '1'
                          all_user_accessable_flg: '1'
                        created_at: '2019-11-13 17:00:11'
                        updated_at: '2019-11-13 17:00:11'
                        created_user_id: null
                        updated_user_id: null
                    first_page_url: 'http://localhost/admin/api/table?page=1'
                    from: 1
                    last_page: 1
                    last_page_url: 'http://localhost/admin/api/table?page=1'
                    next_page_url: null
                    path: 'http://localhost/admin/api/table'
                    per_page: 20
                    prev_page_url: null
                    to: 11
                    total: 11
      description: |-
        #### 処理概要
        * カスタムテーブル一覧を取得する
        * ログインユーザーがアクセスできるテーブルのみ、一覧として取得できる


        #### Exment権限(Permission)
        + システム_システム情報
        + システム_カスタムテーブル
        + システム_すべてのデータ
        + テーブル_テーブル
        + テーブル_すべてのデータの編集
        + テーブル_すべてのデータの閲覧
        + テーブル_すべてのデータの参照
        + テーブル_担当者データの編集
        + テーブル_担当者データの閲覧
        + テーブル_担当者データの閲覧


        #### APIスコープ(scope)
        + table_read
        + table_write


        #### 対応バージョン
        v1.1.0
      parameters:
        - schema:
            type: integer
            default: '20'
            maximum: 100
            minimum: 1
          in: query
          name: count
          description: 1回のリクエストで取得する件数。1～100
      requestBody: {}
      operationId: get-tables
      security:
        - OAuth2認証: []
  '/api/table/{tableKey}':
    parameters:
      - schema:
          type: string
        name: tableKey
        in: path
        required: true
        description: カスタムテーブルのID(Ex. 3)、もしくはテーブル名(Ex. user)
    get:
      summary: カスタムテーブル情報取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTable'
              examples:
                Example:
                  value:
                    id: 8
                    suuid: 5c86fb70562dd56f34c0
                    table_name: information
                    table_view_name: お知らせ
                    description: ユーザーに通知するお知らせです。ダッシュボードなどに表示することができます。
                    system_flg: '0'
                    showlist_flg: '1'
                    order: '0'
                    options:
                      icon: fa-exclamation
                      comment_flg: '0'
                      revision_flg: '0'
                      attachment_flg: '1'
                      one_record_flg: '0'
                      search_enabled: '1'
                      use_label_id_flg: '0'
                      all_user_editable_flg: '0'
                      all_user_viewable_flg: '1'
                      all_user_accessable_flg: '1'
                    created_at: '2019-11-13 17:00:11'
                    updated_at: '2019-11-13 17:08:31'
                    created_user_id: null
                    updated_user_id: '1'
          headers: {}
      description: |
        #### 処理概要
        * カスタムテーブルのIDもしくはテーブル名を指定し、そのカスタムテーブル内のカスタム列情報一覧を取得する
        * ログインユーザーがアクセスできないテーブルの場合、403エラーが発生する

        #### Exment権限(Permission)
        + システム：システム情報
        + システム：カスタムテーブル
        + システム：すべてのデータ
        + テーブル：テーブル
        + テーブル：すべてのデータの編集
        + テーブル：すべてのデータの閲覧
        + テーブル：すべてのデータの参照
        + テーブル：担当者データの編集
        + テーブル：担当者データの閲覧
        + テーブル：担当者データの閲覧

        #### APIスコープ(scope)
        + table_read
        + table_write

        #### 対応バージョン
        v1.1.0
      parameters: []
      security:
        - OAuth2認証: []
      operationId: get-table
  '/api/table/{tableKey}/columns':
    parameters:
      - type: string
        name: tableKey
        in: path
        required: true
        description: カスタムテーブルのID(Ex. 3)、もしくはテーブル名(Ex. user)
    get:
      summary: カスタムテーブル内のカスタム列一覧取得
      tags: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomColumn'
              examples:
                Example:
                  value:
                    - id: 45
                      suuid: 9ce2740b044ea7143a55
                      custom_table_id: '8'
                      column_name: title
                      column_view_name: タイトル
                      column_type: text
                      description: null
                      system_flg: '0'
                      order: '0'
                      options:
                        required: '1'
                        index_enabled: '1'
                      created_at: '2019-11-13 17:00:11'
                      updated_at: '2019-11-13 17:00:15'
                      created_user_id: null
                      updated_user_id: null
                      required: '1'
                      index_enabled: '1'
                      unique: false
                      custom_table:
                        id: 8
                        suuid: 5c86fb70562dd56f34c0
                        table_name: information
                        table_view_name: お知らせ
                        description: ユーザーに通知するお知らせです。ダッシュボードなどに表示することができます。
                        system_flg: '0'
                        showlist_flg: '1'
                        order: '0'
                        options:
                          icon: fa-exclamation
                          comment_flg: '0'
                          revision_flg: '0'
                          attachment_flg: '1'
                          one_record_flg: '0'
                          search_enabled: '1'
                          use_label_id_flg: '0'
                          all_user_editable_flg: '0'
                          all_user_viewable_flg: '1'
                          all_user_accessable_flg: '1'
                        created_at: '2019-11-13 17:00:11'
                        updated_at: '2019-11-13 17:08:31'
                        created_user_id: null
                        updated_user_id: '1'
                    - id: 46
                      suuid: c5ade37d68066e8eb7c4
                      custom_table_id: '8'
                      column_name: body
                      column_view_name: 本文
                      column_type: editor
                      description: null
                      system_flg: '0'
                      order: '0'
                      options:
                        string_length: '2000'
                      created_at: '2019-11-13 17:00:11'
                      updated_at: '2019-11-13 17:00:11'
                      created_user_id: null
                      updated_user_id: null
                      required: false
                      index_enabled: false
                      unique: false
                      custom_table:
                        id: 8
                        suuid: 5c86fb70562dd56f34c0
                        table_name: information
                        table_view_name: お知らせ
                        description: ユーザーに通知するお知らせです。ダッシュボードなどに表示することができます。
                        system_flg: '0'
                        showlist_flg: '1'
                        order: '0'
                        options:
                          icon: fa-exclamation
                          comment_flg: '0'
                          revision_flg: '0'
                          attachment_flg: '1'
                          one_record_flg: '0'
                          search_enabled: '1'
                          use_label_id_flg: '0'
                          all_user_editable_flg: '0'
                          all_user_viewable_flg: '1'
                          all_user_accessable_flg: '1'
                        created_at: '2019-11-13 17:00:11'
                        updated_at: '2019-11-13 17:08:31'
                        created_user_id: null
                        updated_user_id: '1'
      description: |
        #### 処理概要
        * カスタムテーブルのIDもしくはテーブル名を指定し、そのカスタムテーブル内のカスタム列情報一覧を取得する
        * ログインユーザーがアクセスできないテーブルの場合、403エラーが発生する

        #### Exment権限(Permission)
        + システム：システム情報
        + システム：カスタムテーブル
        + システム：すべてのデータ
        + テーブル：テーブル
        + テーブル：すべてのデータの編集
        + テーブル：すべてのデータの閲覧
        + テーブル：すべてのデータの参照
        + テーブル：担当者データの編集
        + テーブル：担当者データの閲覧
        + テーブル：担当者データの閲覧

        #### APIスコープ(scope)
        + table_read
        + table_write

        #### 対応バージョン
        v1.1.0
      security:
        - OAuth2認証: []
      operationId: get-table-columns
  '/api/column/{id}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
        description: カスタム列ID
        schema:
          type: integer
    get:
      summary: カスタム列情報取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomColumn'
              examples:
                Example:
                  value:
                    id: 45
                    suuid: 9ce2740b044ea7143a55
                    custom_table_id: '8'
                    column_name: title
                    column_view_name: タイトル
                    column_type: text
                    description: null
                    system_flg: '0'
                    order: '0'
                    options:
                      required: '1'
                      index_enabled: '1'
                    created_at: '2019-11-13 17:00:11'
                    updated_at: '2019-11-13 17:00:15'
                    created_user_id: null
                    updated_user_id: null
                    required: '1'
                    index_enabled: '1'
                    unique: false
      description: |
        #### 処理概要
        * カスタム列のIDから、カスタム列情報を取得する。
        * ログインユーザーがアクセスできないカスタムテーブルの列だった場合、403エラーが発生する。

        #### Exment権限(Permission)
        + システム：システム情報
        + システム：カスタムテーブル
        + システム：すべてのデータ
        + テーブル：テーブル
        + テーブル：すべてのデータの編集
        + テーブル：すべてのデータの閲覧
        + テーブル：すべてのデータの参照
        + テーブル：担当者データの編集
        + テーブル：担当者データの閲覧
        + テーブル：担当者データの参照

        #### APIスコープ(scope)
        + table_read
        + table_write

        #### 対応バージョン
        v1.1.0
      security:
        - OAuth2認証: []
      operationId: get-column
  '/api/data/{tableKey}':
    parameters:
      - type: string
        name: tableKey
        in: path
        required: true
        schema:
          type: string
        description: テーブル名(Ex. information)
    get:
      summary: カスタムデータ一覧取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CustomValue'
                  - $ref: '#/components/schemas/Paginate'
              examples:
                Example:
                  value:
                    current_page: 1
                    data:
                      - id: 8
                        suuid: 946a85f121a7d9b2ab72
                        parent_type: null
                        parent_id: null
                        value:
                          body: テストです。
                          order: '1'
                          title: テスト
                          priority: 3
                          view_flg: 1
                        created_at: '2019-11-15 16:44:41'
                        updated_at: '2019-11-15 16:44:41'
                        deleted_at: null
                        deleted_user_id: null
                        created_user_id: null
                        updated_user_id: null
                        label: テスト
                      - id: 9
                        suuid: 4c7944646420b5b5c0d3
                        parent_type: null
                        parent_id: null
                        value:
                          body: テストです。
                          order: '1'
                          title: テスト
                          priority: 3
                          view_flg: 1
                        created_at: '2019-11-15 16:48:46'
                        updated_at: '2019-11-15 16:48:46'
                        deleted_at: null
                        deleted_user_id: null
                        created_user_id: '1'
                        updated_user_id: '1'
                        label: テスト
                      - id: 10
                        suuid: 1001025f0f3715dbc80b
                        parent_type: null
                        parent_id: null
                        value:
                          body: テストです。
                          order: '1'
                          title: テスト
                          priority: 3
                          view_flg: 1
                        created_at: '2019-11-15 17:41:54'
                        updated_at: '2019-11-15 17:41:54'
                        deleted_at: null
                        deleted_user_id: null
                        created_user_id: '1'
                        updated_user_id: '1'
                        label: テスト
                    first_page_url: 'http://local-exment/admin/api/data/information?count=20&page=1'
                    from: 1
                    last_page: 1
                    last_page_url: 'http://local-exment/admin/api/data/information?count=20&page=1'
                    next_page_url: null
                    path: 'http://local-exment/admin/api/data/information'
                    per_page: 20
                    prev_page_url: null
                    to: 3
                    total: 3
      description: |
        #### 処理概要
        * 特定のカスタムテーブルに登録している、カスタムデータの一覧を取得する
        * ログインユーザーに権限のあるデータのみ、一覧の対象となる

        #### Exment権限(Permission)
        + システム：システム情報
        + システム：カスタムテーブル
        + システム：すべてのデータ
        + テーブル：テーブル
        + テーブル：すべてのデータの編集
        + テーブル：すべてのデータの閲覧
        + テーブル：すべてのデータの参照
        + テーブル：担当者データの編集
        + テーブル：担当者データの閲覧
        + テーブル：担当者データの参照

        #### APIスコープ(scope)
        + value_read
        + value_write

        #### 対応バージョン
        v1.1.0
      parameters:
        - schema:
            type: integer
            default: '1'
          in: query
          name: page
          description: 取得するページ番号
        - schema:
            type: integer
            maximum: 100
            minimum: 1
            default: '20'
          in: query
          name: count
          description: 1回のリクエストで取得する件数。1～100
        - schema:
            type: string
          in: query
          name: orderby
          description: データの並べ替えを行う場合、並べ替えの列名。複数ある場合はカンマ区切り。逆順は、「id desc」のように半角スペースを追加する
      security:
        - OAuth2認証: []
      operationId: get-values
    post:
      summary: カスタムデータ新規作成
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                  - {}
                type: object
              examples:
                Exaple(1件のみ登録):
                  value:
                    id: 8
                    suuid: 946a85f121a7d9b2ab72
                    parent_type: null
                    parent_id: null
                    value:
                      body: テストです。
                      order: '1'
                      title: テスト
                      priority: 3
                      view_flg: 1
                    created_at: '2019-11-15 16:44:41'
                    updated_at: '2019-11-15 16:44:41'
                    deleted_at: null
                    deleted_user_id: null
                    created_user_id: '1'
                    updated_user_id: '1'
                    label: テスト
                Exaple(複数件登録):
                  value:
                    - id: 10
                      suuid: 1001025f0f3715dbc80b
                      parent_type: null
                      parent_id: null
                      value:
                        body: テストです。
                        order: '1'
                        title: テスト
                        priority: 3
                        view_flg: 1
                      created_at: '2019-11-15 17:41:54'
                      updated_at: '2019-11-15 17:41:54'
                      deleted_at: null
                      deleted_user_id: null
                      created_user_id: '1'
                      updated_user_id: '1'
                      label: テスト
                    - id: 11
                      suuid: 273dda2cfcd1e0a21708
                      parent_type: null
                      parent_id: null
                      value:
                        body: テストです2。
                        order: '2'
                        title: テスト2
                        priority: 4
                        view_flg: 1
                      created_at: '2019-11-15 17:41:54'
                      updated_at: '2019-11-15 17:41:54'
                      deleted_at: null
                      deleted_user_id: null
                      created_user_id: '1'
                      updated_user_id: '1'
                      label: テスト2
      description: "#### 処理概要\n* カスタムテーブルに、データを新規作成する\n* ログインユーザーがカスタムテーブルに新規追加する権限のない場合、403エラーが発生する\n* 登録を行いたいデータは、value配列内に値を代入してPOSTする\n\n#### Exment権限(Permission)\n+ システム：システム情報\n+ システム：カスタムテーブル\n+ システム：すべてのデータ\n+ テーブル：テーブル\n+ テーブル：すべてのデータの編集\n+ テーブル：担当者データの編集\n\n#### APIスコープ(scope)\n+ value_write\n\n#### 対応バージョン\nv1.1.0\n\n\n#### 複数件登録する場合\n* POSTデータを、配列で複数件送信することで、複数データを登録することができる\n* 1件でもエラーが発生した場合は、すべてのデータを登録しない\n* 1度に登録できる件数は100件まで\n\n#### カスタム列の種類が「選択肢 (他のテーブルの値一覧から選択)」で、id以外をキーとして新規作成を行いたい場合\nパラメータ「findKeys」を追加することにより、id以外の値をキーとできます。  \n例：「契約」テーブルのカスタムデータを登録時、列「顧客(customer)」のデータを、「顧客」テーブル内の「顧客名(customer_code)」を使用したい場合  \n\n■通常時：\n```\n{\n    value: {\n        'contract_code': 'C00001',\n        'customer': '1'\n    }\n}\n```\n\n■findKeys使用時：\n```\n{\n    value: {\n        'contract_code': 'C00001',\n        'customer': '株式会社ABC'\n    },\n    findKeys: {\n        'customer': 'customer_name'\n    }\n}\n```"
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  oneOf:
                    - type: object
                      description: (1)登録するデータ。1件のみの場合。項目は、登録するテーブルのカスタム列に合わせる
                      properties:
                        body:
                          type: string
                        title:
                          type: string
                        priority:
                          type: integer
                        order:
                          type: integer
                        view_flg:
                          type: integer
                    - type: array
                      description: (2)登録するデータ。複数件登録する場合
                      items:
                        type: object
                        description: 項目は、登録するテーブルのカスタム列に合わせる
                        properties:
                          body:
                            type: string
                          title:
                            type: string
                          priority:
                            type: integer
                          order:
                            type: integer
                          view_flg:
                            type: integer
                  description: ※1件登録するか、複数件登録するかで、送信するパラメータが変更になる
                findKeys:
                  type: object
                  description: スタム列の種類が「選択肢 (他のテーブルの値一覧から選択)」で、id以外をキーとして新規作成を行いたい場合。項目は、登録するテーブルのカスタム列に合わせる
                  properties:
                    (column_name):
                      type: string
                      description: 参照先のテーブルのカラム名を設定
        description: ''
      security:
        - OAuth2認証: []
      operationId: post-values
  '/api/data/{tableKey}/query':
    parameters:
      - type: string
        name: tableKey
        in: path
        required: true
        schema:
          type: string
        description: テーブル名(Ex. information)
    get:
      summary: カスタムデータ検索
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                    default: 1
                    description: 現在のページ
                  first_page_url:
                    type: string
                    description: 最初のページのURL
                  last_page:
                    type: integer
                    description: 最後のページ番号
                  path:
                    type: string
                  per_page:
                    type: integer
                    description: 1ページあたりの表示件数
                  to:
                    type: integer
                    description: 表示しているデータの終了番号
                  total:
                    type: integer
                    description: データの全件数
                  from:
                    type: integer
                    description: 表示しているデータの開始番号
                  last_page_url:
                    type: string
                    description: 最後のページのURL
                  prev_page_url:
                    type: string
                    description: 前のページのURL
                  next_page_url:
                    type: string
                    description: 次のページのURL
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CustomValue'
              examples:
                Example:
                  value:
                    current_page: 1
                    data:
                      - id: 1
                        suuid: 39c97ba08c6e392a125a
                        parent_type: null
                        parent_id: null
                        value:
                          body: '<p>Exmentは、かんたん、お手頃なデータ管理Webシステムです。&nbsp;</p>'
                          order: '5'
                          title: Exmentへようこそ！
                          priority: '3'
                          view_flg: '1'
                        created_at: '2019-01-04 18:48:15'
                        updated_at: '2019-01-04 19:50:55'
                        deleted_at: null
                        deleted_user_id: null
                        created_user_id: null
                        updated_user_id: null
                        label: Exmentへようこそ！
                        workflow_value: null
                    first_page_url: 'http://local-exment/admin/api/data/information/query?q=Exment&count=20&page=1'
                    from: 1
                    last_page: 1
                    last_page_url: 'http://local-exment/admin/api/data/information/query?q=Exment&count=20&page=1'
                    next_page_url: null
                    path: 'http://local-exment/admin/api/data/information/query'
                    per_page: 20
                    prev_page_url: null
                    to: 1
                    total: 1
      description: |-
        #### 処理概要
        * 特定のカスタムテーブルに登録している、カスタムデータを検索する
        * ログインユーザーに権限のあるデータのみ、一覧の対象となる
        * 「検索インデックス」に登録している列が、検索対象列となる
        * 検索は前方一致。全文一致で検索を行いたい場合は、<a href="https://exment.net/docs/#/ja/search?id=%e8%a3%9c%e8%b6%b3%e3%83%87%e3%83%bc%e3%82%bf%e6%a4%9c%e7%b4%a2%e3%82%92%e9%83%a8%e5%88%86%e4%b8%80%e8%87%b4%e3%81%ab%e5%88%87%e3%82%8a%e6%9b%bf%e3%81%88" target="_blank">こちら</a>に従い、設定が必要

        #### Exment権限(Permission)
        + システム：システム情報
        + システム：カスタムテーブル
        + システム：すべてのデータ
        + テーブル：テーブル
        + テーブル：すべてのデータの編集
        + テーブル：すべてのデータの閲覧
        + テーブル：すべてのデータの参照
        + テーブル：担当者データの編集
        + テーブル：担当者データの閲覧
        + テーブル：担当者データの参照

        #### APIスコープ(scope)
        + value_read
        + value_write

        #### 対応バージョン
        v2.1.6
      parameters:
        - schema:
            type: string
          in: query
          name: q
          description: 検索文字列
          required: true
        - schema:
            type: integer
            default: '1'
          in: query
          name: page
          description: 取得するページ番号
          required: true
        - schema:
            type: integer
            default: '20'
            maximum: 100
            minimum: 1
          in: query
          name: count
          description: 1回のリクエストで取得する件数。1～100
          required: true
      security:
        - OAuth2認証: []
      operationId: get-values-seach
  '/api/data/{tableKey}/{id}':
    parameters:
      - type: string
        name: tableKey
        in: path
        required: true
        description: テーブル名(Ex. information)
        schema:
          type: string
      - type: string
        name: id
        in: path
        required: true
        description: カスタムデータのID
        schema:
          type: integer
    get:
      summary: カスタムデータ情報取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomValue'
              examples:
                Example:
                  value:
                    id: 8
                    suuid: 946a85f121a7d9b2ab72
                    parent_type: null
                    parent_id: null
                    value:
                      body: テストです。
                      order: '1'
                      title: テスト
                      priority: 3
                      view_flg: 1
                    created_at: '2019-11-15 16:44:41'
                    updated_at: '2019-11-15 16:44:41'
                    deleted_at: null
                    deleted_user_id: null
                    created_user_id: null
                    updated_user_id: null
                    label: テスト
      description: |-
        #### 処理概要
        * 特定のカスタムテーブルに登録している、カスタムデータ情報を取得する
        * ログインユーザーに権限のないデータだった場合、403エラーが発生する

        #### Exment権限(Permission)
        + システム：システム情報
        + システム：カスタムテーブル
        + システム：すべてのデータ
        + テーブル：テーブル
        + テーブル：すべてのデータの編集
        + テーブル：すべてのデータの閲覧
        + テーブル：すべてのデータの参照
        + テーブル：担当者データの編集
        + テーブル：担当者データの閲覧
        + テーブル：担当者データの参照

        #### APIスコープ(scope)
        + value_read
        + value_write

        #### 対応バージョン
        v1.1.0
      requestBody: {}
      security:
        - OAuth2認証: []
      operationId: get-value
    put:
      summary: カスタムデータ情報更新
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomValue'
              examples:
                Example:
                  value:
                    id: 8
                    suuid: 946a85f121a7d9b2ab72
                    parent_type: null
                    parent_id: null
                    value:
                      body: テストです。
                      order: '1'
                      title: テスト更新
                      priority: 3
                      view_flg: 1
                    created_at: '2019-11-15 16:44:41'
                    updated_at: '2019-11-15 18:01:34'
                    deleted_at: null
                    deleted_user_id: null
                    created_user_id: null
                    updated_user_id: '1'
                    label: テスト更新
      description: "#### 処理概要\n* カスタムデータ情報を更新する\n* ログインユーザーに権限のないデータだった場合、403エラーが発生する\n* 更新が発生する列の情報のみ、value配列内に値を代入してPUTする\n\n\n#### Exment権限(Permission)\n+ システム：システム情報\n+ システム：カスタムテーブル\n+ システム：すべてのデータ\n+ テーブル：テーブル\n+ テーブル：すべてのデータの編集\n+ テーブル：担当者データの編集\n\n#### APIスコープ(scope)\n+ value_write\n\n#### 対応バージョン\nv1.1.0\n\n#### カスタム列の種類が「選択肢 (他のテーブルの値一覧から選択)」で、id以外をキーとして更新を行いたい場合\nパラメータ「findKeys」を追加することにより、id以外の値をキーとできます。  \n例：「契約」テーブルのカスタムデータを更新時、列「顧客(customer)」のデータを、「顧客」テーブル内の「顧客名(customer_code)」を使用したい場合  \n\n■通常時：\n```\n{\n    value: {\n        'contract_code': 'C00001',\n        'customer': '1'\n    }\n}\n```\n\n■findKeys使用時：\n```\n{\n    value: {\n        'contract_code': 'C00001',\n        'customer': '株式会社ABC'\n    },\n    findKeys: {\n        'customer': 'customer_name'\n    }\n}\n```\n"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: ''
              properties:
                value:
                  type: object
                  description: 項目は、登録するテーブルのカスタム列に合わせる
                  properties:
                    view_flg:
                      type: integer
                    order:
                      type: integer
                    priority:
                      type: integer
                    title:
                      type: string
                    body:
                      type: string
                findKeys:
                  type: object
                  description: スタム列の種類が「選択肢 (他のテーブルの値一覧から選択)」で、id以外をキーとして新規作成を行いたい場合。項目は、登録するテーブルのカスタム列に合わせる
                  properties:
                    (column_name):
                      type: string
                      description: 参照先のテーブルのカラム名を設定
            examples:
              Example: {}
      security:
        - OAuth2認証: []
      operationId: put-value
    delete:
      summary: カスタムデータ情報削除
      responses:
        '204':
          description: No Content
      description: |
        #### 処理概要
        * カスタムデータ情報を論理削除する
        * ログインユーザーに権限のないデータだった場合、403エラーが発生する


        #### Exment権限(Permission)
        + システム：システム情報
        + システム：カスタムテーブル
        + システム：すべてのデータ
        + テーブル：テーブル
        + テーブル：すべてのデータの編集
        + テーブル：担当者データの編集

        #### APIスコープ(scope)
        + value_write

        #### 対応バージョン
        v1.1.0
      security:
        - OAuth2認証: []
      operationId: delete-value
components:
  schemas:
    CustomTable:
      title: CustomTable
      description: カスタムテーブル情報
      x-examples:
        example-1: {}
      allOf:
        - type: object
          properties:
            id:
              type: integer
            table_name:
              type: string
              description: テーブル名(英数字)
            table_view_name:
              type: string
              description: テーブル表示名
            description:
              type: string
              description: 説明文
            system_flg:
              type: boolean
              default: 0
              description: システムによって作成されたテーブルかどうか
            showlist_flg:
              type: boolean
              default: 0
              description: 一覧に表示するかどうか
            order:
              type: integer
              description: 並び順
            options:
              type: object
              properties:
                icon:
                  type: string
                  description: Font-awesomeアイコン
                comment_flg:
                  type: boolean
                  description: コメント機能を使用
                  default: true
                attachment_flg:
                  type: boolean
                  description: 添付機能を使用
                  default: true
                one_record_flg:
                  type: boolean
                  default: false
                  description: 1件のみのデータかどうか
                search_enabled:
                  type: boolean
                  default: true
                  description: 検索を許可するか
                all_user_editable_flg:
                  type: boolean
                  default: false
                  description: すべてのユーザーが、編集を許可するか
                all_user_viewable_flg:
                  default: false
                  description: すべてのユーザーが、閲覧を許可するか
                  type: boolean
                all_user_accessable_flg:
                  type: boolean
                  default: false
                  description: すべてのユーザーが、参照を許可するか
          required:
            - table_name
            - table_view_name
            - system_flg
            - showlist_flg
            - order
            - id
        - $ref: '#/components/schemas/ModelBase'
    CustomColumn:
      title: CustomColumn
      description: カスタム列情報
      allOf:
        - type: object
          properties:
            id:
              type: integer
            column_name:
              type: string
              description: カラム名(英数字)
            column_view_name:
              type: string
              description: カラム表示名
            required:
              type: boolean
              default: true
              description: 必須列かどうか
            index_enabled:
              type: boolean
              default: 1
              description: 検索インデックス列かどうか
            unique:
              type: boolean
              default: 1
              description: ユニーク列かどうか
            column_type:
              type: string
              description: 列種類
            custom_table_id:
              type: integer
              description: カスタムテーブルのid
          required:
            - id
            - column_name
            - column_view_name
            - required
            - index_enabled
            - unique
            - column_type
            - custom_table_id
        - $ref: '#/components/schemas/ModelBase'
    CustomValue:
      title: CustomValue
      description: カスタムデータ情報
      allOf:
        - type: object
          properties:
            id:
              type: integer
              description: id
            value:
              description: 画面で入力したデータのkey-value列
              type: object
            parent_id:
              type: integer
              description: そのデータに親データがある場合、親テーブルのカスタムデータのid
            parent_type:
              type: string
              description: そのデータに親データがある場合、親テーブル名
            label:
              description: そのデータを画面表示するときの見出し(読み取り専用)
              type: string
            deleted_at:
              type: string
              description: 削除日時
            deteled_user_id:
              type: integer
              description: 削除ユーザーID
          required:
            - id
        - $ref: '#/components/schemas/ModelBase'
    Paginate:
      title: Paginate
      type: object
      description: 一覧の結果モデル
      properties:
        current_page:
          type: integer
          default: 1
          description: 現在のページ
        first_page_url:
          type: string
          description: 最初のページのURL
        last_page:
          type: integer
          description: 最後のページ番号
        path:
          type: string
        per_page:
          type: integer
          description: 1ページあたりの表示件数
        to:
          type: integer
          description: 表示しているデータの終了番号
        total:
          type: integer
          description: データの全件数
        from:
          type: integer
          description: 表示しているデータの開始番号
        last_page_url:
          type: string
          description: 最後のページのURL
        prev_page_url:
          type: string
          description: 前のページのURL
        next_page_url:
          type: string
          description: 次のページのURL
    ModelBase:
      title: ModelBase
      type: object
      description: Exmentモデルの基底クラス
      properties:
        id:
          type: integer
          description: id
        created_at:
          description: 作成日時
          type: string
        updated_at:
          description: 更新日時
          type: string
        updated_user_id:
          description: 更新ユーザーID
          type: integer
        created_user_id:
          description: 作成ユーザーID
          type: integer
      required:
        - id
    Workflow:
      title: Workflow
      description: ワークフロー情報
      allOf:
        - type: object
          properties:
            id:
              type: integer
              description: ID
            workflow_type:
              type: integer
              description: (未利用)
            workflow_view_name:
              type: string
              description: ワークフロー表示名
            start_status_name:
              type: string
              description: 開始ステータス名
            setting_completed_flg:
              type: integer
              default: 0
              description: 設定完了フラグ
          required:
            - id
            - workflow_view_name
            - start_status_name
            - setting_completed_flg
        - $ref: '#/components/schemas/ModelBase'
    WorkflowStatus:
      title: WorkflowStatus
      description: ワークフローステータス情報
      allOf: []
  securitySchemes:
    OAuth2認証:
      type: oauth2
      flows:
        password:
          tokenUrl: /oauth/token
          refreshUrl: /oauth/token
          scopes: []
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/token
          refreshUrl: /oauth/token
          scopes: []
